In [18]:
import pandas as pd
import numpy as np

In [19]:
#reading the input data from the csv file
INPUT_PATH="carTrainData.csv"

In [20]:
#header values are defined.
headers = ["buying price", "maint cost", "doors", "persons", "lug_boot", "safety", "v7"]

In [21]:
dataset = pd.read_csv(INPUT_PATH, header=None, names=headers, na_values="?" )
dataset = dataset.iloc[1:]

In [22]:
dataset

buying price maint cost  doors persons lug_boot safety     v7
1           vhigh      vhigh      2       2    small    low  unacc
2           vhigh      vhigh      2       2    small   high  unacc
3           vhigh      vhigh      2       2      med    low  unacc
4           vhigh      vhigh      2       2      med    med  unacc
5           vhigh      vhigh      2       2      med   high  unacc
6           vhigh      vhigh      2       2      big    low  unacc
7           vhigh      vhigh      2       2      big   high  unacc
8           vhigh      vhigh      2       4    small    low  unacc
9           vhigh      vhigh      2       4    small    med  unacc
10          vhigh      vhigh      2       4      med    low  unacc
11          vhigh      vhigh      2       4      med   high  unacc
12          vhigh      vhigh      2       4      big    low  unacc
13          vhigh      vhigh      2       4      big    med  unacc
14          vhigh      vhigh      2       4      big   high  unacc
15          vhigh      vhigh      2    more    small    low  unacc
16          vhigh      vhigh      2    more    small    med  unacc
17          vhigh      vhigh      2    more    small   high  unacc
18          vhigh      vhigh      2    more      med    low  unacc
19          vhigh      vhigh      2    more      med    med  unacc
20          vhigh      vhigh      2    more      med   high  unacc
21          vhigh      vhigh      2    more      big    low  unacc
22          vhigh      vhigh      2    more      big    med  unacc
23          vhigh      vhigh      2    more      big   high  unacc
24          vhigh      vhigh      3       2    small    med  unacc
25          vhigh      vhigh      3       2    small   high  unacc
26          vhigh      vhigh      3       2      med    low  unacc
27          vhigh      vhigh      3       2      med    med  unacc
28          vhigh      vhigh      3       2      med   high  unacc
29          vhigh      vhigh      3       2      big    low  unacc
30          vhigh      vhigh      3       2      big    med  unacc
...           ...        ...    ...     ...      ...    ...    ...
1399          low        low      4       4      med    med   good
1400          low        low      4       4      med   high  vgood
1401          low        low      4       4      big    low  unacc
1402          low        low      4       4      big    med   good
1403          low        low      4       4      big   high  vgood
1404          low        low      4    more    small   high   good
1405          low        low      4    more      med    low  unacc
1406          low        low      4    more      med    med   good
1407          low        low      4    more      med   high  vgood
1408          low        low      4    more      big    low  unacc
1409          low        low      4    more      big    med   good
1410          low        low  5more       2    small    low  unacc
1411          low        low  5more       2      med    med  unacc
1412          low        low  5more       2      med   high  unacc
1413          low        low  5more       2      big    low  unacc
1414          low        low  5more       2      big    med  unacc
1415          low        low  5more       2      big   high  unacc
1416          low        low  5more       4    small    low  unacc
1417          low        low  5more       4    small    med    acc
1418          low        low  5more       4    small   high   good
1419          low        low  5more       4      med    low  unacc
1420          low        low  5more       4      med    med   good
1421          low        low  5more       4      med   high  vgood
1422          low        low  5more       4      big    med   good
1423          low        low  5more    more    small    low  unacc
1424          low        low  5more    more    small   high   good
1425          low        low  5more    more      med    med   good
1426          low        low  5more    more      med

In [23]:
#here the feature values are converted to categorical values
for header in headers:
    dataset[header]=dataset[header].astype("category")
    dataset[header]=dataset[header].cat.codes    

In [24]:
#the first 6 column values are the feature values
training_array=dataset.iloc[:,0:6].values
#arr1.dtype

In [41]:
#the last column values are the target attribute values
target_array=dataset.iloc[:,6:7].values
#list(map(str, np.unique(target_array)))

In [27]:
#importing the decision tree classifier from the sklearn library
from sklearn import tree 
classifier = tree.DecisionTreeClassifier(criterion="entropy")
classifier.fit(training_array, target_array)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
#import graphviz

In [30]:
#dot_data = tree.export_graphviz(classifier, out_file=None)

In [35]:
#graph = graphviz.Source(dot_data)
#dot_data = tree.export_graphviz(classifier, out_file=None, 
#                         feature_names=headers[0:6],  
#                         class_names=list(map(str, np.unique(target_array))),  
#                         filled=True, rounded=True,  
#                         special_characters=True)

In [36]:
#graph = graphviz.Source(dot_data)
#graph

In [46]:
#we are getting the target feature values predicted by the classifier
training_prediction = classifier.predict(training_array)

In [48]:
#calculating the Accuracy of the classifier for the train data
from sklearn.metrics import accuracy_score
train_accuracy_score = accuracy_score(target_array, training_prediction)
print("Train accuracy score: ", train_accuracy_score)

Train accuracy score:  1.0


In [51]:
#calculating the confusion matrix of the classifier for the train data
from sklearn.metrics import confusion_matrix
train_confusion_matrix = confusion_matrix(target_array, training_prediction)
print( "Training Confusion matrix: \n", train_confusion_matrix)

Training Confusion matrix  [[ 307    0    0    0]
 [   0   57    0    0]
 [   0    0 1013    0]
 [   0    0    0   51]]


In [77]:
#reading the test data from the file
testDataSet = pd.read_csv("carTestData.csv", header=None, names=headers, na_values="?")
testDataSet = testDataSet[1:]
#here the feature values are converted to categorical values
for header in headers:
    testDataSet[header]=testDataSet[header].astype("category")
    testDataSet[header]=testDataSet[header].cat.codes   

In [78]:
#we are splitting the testDataSet to obtain the feature and target data
test_feature = testDataSet.iloc[:,0:6]
test_target = testDataSet.iloc[:,6:7]

In [85]:
#we are predicting the target attribute values using the classifier
test_prediction = classifier.predict(test_feature)

In [86]:
#calculating the Accuracy of the classifier for the test data
test_accuracy_score = accuracy_score(test_target, test_prediction)
print("Test accuracy score: ", test_accuracy_score)

Test accuracy score:  1.0


In [88]:
#calculating the confusion matrix of the classifier for the test data
from sklearn.metrics import confusion_matrix
test_confusion_matrix = confusion_matrix(test_target, test_prediction)
print( "Test Confusion matrix: \n", test_confusion_matrix)

Test Confusion matrix: 
 [[ 307    0    0    0]
 [   0   57    0    0]
 [   0    0 1013    0]
 [   0    0    0   51]]
